### ISSUE TITLE
Please remove this content

### ISSUE THREAD

**Issue by ceilingfish** [backenddeveloper/ForCrisp#1]
Hello,
My name is Tom Parrish, and I'm a developer at Crisp Thinking. My apologies that this was not clearly conveyed to you at the time, but these test questions and answers are considered copyright of Crisp Thinking. This is to prevent copies of the test results being available to other candidates who search for answers on github.

Can you please mark this repository as private, or remove it.

Many Thanks
Tom Parrish

**Comment by backenddeveloper** [comment]
Dear Tom, @ceilingfish 

Thank you for your comment.

I am happy to remove the repository. To be blunt it is not in the better half of technical tests that I have been offered in the last five years; and in my opinion, to be even tangentially associated with Crisp Thinking is a negative to one's reputation as an engineer.

I would however like to point out that your statement here:
_"My apologies that this was not clearly conveyed to you at the time"[sic]_
And your statement on your DCMA notice:
_"The candidate will have received a standard disclaimer with the test stating that our questions and their answers are copyright to Crisp Thinking"[sic]_
Are directly contradictory. Therefore one or more of them must be false.

Having retained a copy of the original email from the recruitment agent, whom you authorized to act directly on your behalf, dated [Wed 07/10/2015 13:00]: Your DCMA notice affidavit is false; no disclaimers, licenses or other copyright statements were supplied with the Zip archive containing flat code.

Furthermore your company supplied feedback on, and requested an update to one of, the answers sent to you in a link to Github, which your company requested after you were unable to extract the original Tarball. *Opps!*

To offer a personal note, and to end this conversation: I am happy to remove this repository because it has no longer has any educational value, and I want nothing more to do with your company. In my honest opinion I feel that the further I am from hearing the name Crisp Thinking, the closer I am to being a happy, healthy developer.

Best wishes,

Backenddeveloper

**Comment by ceilingfish** [comment]
Thanks for your understanding on this issue, Graham.

Regards
Tom Parrish
